spring:
  datasource:
    jdbcUrl: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false